name: iOS-ipa-build
on:
  workflow_dispatch:
jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - run: flutter pub get


      - name: Install pods
        run: |
          cd ios
          pod install
      
      - name: Update pods repo
        run: |
          cd ios
          pod repo update
          
      - run: flutter build ios --release --no-codesign
      
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.2
          overwrite: true
          body: "Release v1.2"
